// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwcgI2mwnWdm0FXTH0IeUwkgPnPNwdyE8',
    appId: '1:1043587575346:web:e8a1c3fedba53a84be562b',
    messagingSenderId: '1043587575346',
    projectId: 'ajay-3815b',
    authDomain: 'ajay-3815b.firebaseapp.com',
    databaseURL: 'https://ajay-3815b-default-rtdb.firebaseio.com',
    storageBucket: 'ajay-3815b.appspot.com',
    measurementId: 'G-L7HRHRTMML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADy5C3w69GWa0l9Z8fl_akYHjL6SR9OKs',
    appId: '1:1043587575346:android:ea58184ddae863afbe562b',
    messagingSenderId: '1043587575346',
    projectId: 'ajay-3815b',
    databaseURL: 'https://ajay-3815b-default-rtdb.firebaseio.com',
    storageBucket: 'ajay-3815b.appspot.com',
  );
}
